### ISSUE TITLE
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child |     raise child_exception | OSError: [Errno 8] Exec format error | WARNING: exit code 1 from a shell command

### ISSUE THREAD

**Issue by yohitkumAR** [webosose/chromium68#16]
Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "i686-linux"
NATIVELSBSTRING      = "ubuntu-14.04"
TARGET_SYS           = "arm-webos-linux-gnueabi"
MACHINE              = "raspberrypi3"
DISTRO               = "webos"
DISTRO_VERSION       = "1.0.g"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU           = "hard"
WEBOS_DISTRO_RELEASE_CODENAME = "webos-master"
WEBOS_DISTRO_BUILD_ID = "unofficial"
WEBOS_DISTRO_TOPDIR_REVISION = "375821d1a6baf4dff4308c10b9096bd610651aa1"
WEBOS_DISTRO_TOPDIR_DESCRIBE = "builds/master/84"
DATETIME             = "20190717034900"
meta-webos-ros2      
meta-webos-raspberrypi = "master:4e3ddd50b077d09ef13a1ccf734d63b483dc321c"
meta-raspberrypi     = "thud:c71d79efc5a06a0c896c278c94f5b14413bb4d69"
meta-webos           = "master:4e3ddd50b077d09ef13a1ccf734d63b483dc321c"
meta-ros2            = "master:577f3715047474289341f0fa96ffe55389a45068"
meta-webos-backports-2.8 
meta-webos-backports-2.7 = "master:4e3ddd50b077d09ef13a1ccf734d63b483dc321c"
meta-qt5             = "krogoth:dcfcb581ec65ef1b96f4840a81ea9d9f2297b394"
meta-qt5-compat      = "master:4e3ddd50b077d09ef13a1ccf734d63b483dc321c"
meta-filesystems     
meta-python          
meta-networking      
meta-multimedia      
meta-oe              = "thud:9b3b907f30b0d5b92d58c7e68289184fda733d3e"
meta                 = "thud:f162d5bfe6eaeca24f441c83c87252c8d05744fc"
meta-gplv2           = "thud:aabc30f3bd03f97326fb8596910b94639fea7575"

Initialising tasks: 100% |####################################################################################################################################################################| Time: 0:00:36
Sstate summary: Wanted 1474 Found 0 Missed 1474 Current 1384 (0% match, 48% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: webruntime-68.0.3440.106-58-r17 do_configure: Function failed: do_configure (log file is located at /home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/temp/log.do_configure.24541)
ERROR: Logfile of failure stored in: /home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/temp/log.do_configure.24541
Log data follows:
| DEBUG: Executing shell function do_configure
| GN_ARGS is cros_host_ar="ar" cros_host_cc="gcc " cros_host_cxx="g++ " cros_host_extra_ldflags="-L/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/usr/lib -L/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/lib -Wl,-rpath-link,/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/usr/lib -Wl,-rpath-link,/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/lib -Wl,-rpath,/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/usr/lib -Wl,-rpath,/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot-native/lib -Wl,-O1" cros_target_ar="arm-webos-linux-gnueabi-ar" cros_target_cc="arm-webos-linux-gnueabi-gcc -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot" cros_target_cxx="arm-webos-linux-gnueabi-g++ -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 --sysroot=/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot" enable_memorymanager_webapi=true ffmpeg_branding="Chrome" host_os="linux" is_app_shell_cbe=true is_clang=false is_cross_linux_build=true is_webos=true ozone_auto_platforms=false ozone_platform_wayland_external=true proprietary_codecs=true target_os="linux" target_sysroot="/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/recipe-sysroot" treat_warnings_as_errors=false use_cbe=true use_cups=false use_custom_libcxx=false use_custom_libcxx_for_host=true use_kerberos=false use_ozone=true use_pmlog=true use_sysroot=false use_system_debugger_abort=true use_webos_v8_snapshot=true use_xkbcommon=true is_debug=false symbol_level=0 remove_webcore_debug_symbols=true use_gst_media=true enable_webm_video_codecs=false use_jumbo_build=true jumbo_file_merge_limit=8 use_webos_gpu_info_collector=false use_lttng=false use_neva_media=true is_host_clang=true host_toolchain="//build/toolchain/yocto:clang_yocto_native" fatal_linker_warnings=false enable_nacl=false disable_ftp_support=true enable_print_preview=false enable_remoting=false use_gnome_keyring=false use_pulseaudio=false linux_use_bundled_binutils=false use_debug_fission=false use_gold=true target_cpu="arm" arm_arch="armv7ve" arm_version=7 arm_float_abi="hard"
| BUILD_TARGETS are webos:weboswebruntime app_shell
| Traceback (most recent call last):
|   File "/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/git/depot_tools/gn.py", line 71, in <module>
|     sys.exit(main(sys.argv))
|   File "/home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/git/depot_tools/gn.py", line 66, in main
|     return subprocess.call([gn_path] + args[1:])
|   File "/usr/lib/python2.7/subprocess.py", line 522, in call
|     return Popen(*popenargs, **kwargs).wait()
|   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
|     errread, errwrite)
|   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
|     raise child_exception
| OSError: [Errno 8] Exec format error
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/hmiroot/build-webos/BUILD/work/raspberrypi3-webos-linux-gnueabi/webruntime/68.0.3440.106-58-r17/temp/log.do_configure.24541)
ERROR: Task (/home/hmiroot/build-webos/meta-webosose/meta-webos/recipes-webos/chromium/webruntime.bb:do_configure) failed with exit code '1'

**Comment by jaragunde** [comment]
I noticed `BUILD_SYS = "i686-linux"`, this is a 32-bit system. I don't think we have ever tried to build the web runtime from a 32-bit system, and it's likely unsupported by Chromium.

Would it be possible for you to try building on a 64-bit system?

**Comment by yohitkumAR** [comment]
@jaragunde Thank you for your response. Unfortunately  I don't have 64 bit machine with me. Please let me know if can be done using some other way on 32-bit system.
